[package]
name = "jz-action"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow =  "1.0.86"
serde = {version ="1.0.203", features = ["derive"]}
serde_json = {version = "1.0.117"}
bimap = "0.6.3"
uuid = {version="1.8.0", features = ["v4","serde"]}
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
kube = { version = "0.91.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.22.0", features = ["latest"] }

[dev-dependencies]
arrayvec = {version="0.7.4", features= ["serde"]}