apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jz-action-fs
provisioner: jzaction/nfs-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
mountOptions: 
  - lock
  - nfsvers=3