kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: default
spec:
  storageClassName: jz-flow-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi