apiVersion: v1
kind: ServiceAccount
metadata:
  name: jz-flow-fs-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jz-flow-fs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-jz-flow-fs-provisioner
subjects:
  - kind: ServiceAccount
    name: jz-flow-fs-provisioner
    # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: ClusterRole
  name: jz-flow-fs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-jz-flow-fs-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-jz-flow-fs-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jz-flow-fs-provisioner
    # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-jz-flow-fs-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jz-flow-fs-provisioner
  labels:
    app: jz-flow-fs-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jz-flow-fs-provisioner
  template:
    metadata:
      labels:
        app: jz-flow-fs-provisioner
    spec:
      serviceAccountName: jz-flow-fs-provisioner
      containers:
        - name: jz-flow-fs-provisioner
          image: eipwork/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: jz-flow-fs-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: jzaction/nfs-provisioner
            - name: NFS_SERVER
              value: 192.168.3.163
            - name: NFS_PATH
              value: /hdd1/testdir
      volumes:
        - name: jz-flow-fs-root
          nfs:
            server: 192.168.3.163
            path: /hdd1/testdir
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jz-flow-fs
provisioner: jzaction/nfs-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
mountOptions: 
  - lock
  - nfsvers=3
