name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Build image
      run: |
        eval $(minikube -p minikube docker-env)
        make minikube-docker
      
    - name: Run tests
      run: cargo test --verbose --workspace
